# Generated by Django 5.1a1 on 2024-06-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HaqqApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='skillsRequired',
        ),
    ]
